services:

  purr_w_rest:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: purr_w_rest
    ports:
      - "4004:4004"
    expose:
      - "4004"
    volumes:
      - .:/app
      - /app/node_modules

  purr_w_db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    container_name: purr_w_db
    volumes:
      - ~/apps/purr_w_db:/var/lib/postgresql/data
    ports:
      - "4005:4005"
    expose:
      - "4005"
    command: -p 4005